########## MACROS ###########################################################################
#############################################################################################

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


########### FOUND PACKAGE ###################################################################
#############################################################################################

include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated FindnetCDF.cmake")
set(netCDF_FOUND 1)
set(netCDF_VERSION "4.7.4")

find_package_handle_standard_args(netCDF REQUIRED_VARS
                                  netCDF_VERSION VERSION_VAR netCDF_VERSION)
mark_as_advanced(netCDF_FOUND netCDF_VERSION)

set(netCDF_COMPONENTS netCDF::netcdf)

if(netCDF_FIND_COMPONENTS)
    foreach(_FIND_COMPONENT ${netCDF_FIND_COMPONENTS})
        list(FIND netCDF_COMPONENTS "netCDF::${_FIND_COMPONENT}" _index)
        if(${_index} EQUAL -1)
            conan_message(FATAL_ERROR "Conan: Component '${_FIND_COMPONENT}' NOT found in package 'netCDF'")
        else()
            conan_message(STATUS "Conan: Component '${_FIND_COMPONENT}' found in package 'netCDF'")
        endif()
    endforeach()
endif()

########### VARIABLES #######################################################################
#############################################################################################


set(netCDF_INCLUDE_DIRS "C:/Users/johannes/.conan/data/netcdf/4.7.4/_/_/package/1566203a061d8ac21e9e8d90197c38a777e99c35/include")
set(netCDF_INCLUDE_DIR "C:/Users/johannes/.conan/data/netcdf/4.7.4/_/_/package/1566203a061d8ac21e9e8d90197c38a777e99c35/include")
set(netCDF_INCLUDES "C:/Users/johannes/.conan/data/netcdf/4.7.4/_/_/package/1566203a061d8ac21e9e8d90197c38a777e99c35/include")
set(netCDF_RES_DIRS )
set(netCDF_DEFINITIONS "-DDLL_NETCDF")
set(netCDF_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(netCDF_COMPILE_DEFINITIONS "DLL_NETCDF")
set(netCDF_COMPILE_OPTIONS_LIST "" "")
set(netCDF_COMPILE_OPTIONS_C "")
set(netCDF_COMPILE_OPTIONS_CXX "")
set(netCDF_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(netCDF_LIBRARIES "") # Will be filled later
set(netCDF_LIBS "") # Same as netCDF_LIBRARIES
set(netCDF_SYSTEM_LIBS )
set(netCDF_FRAMEWORK_DIRS )
set(netCDF_FRAMEWORKS )
set(netCDF_FRAMEWORKS_FOUND "") # Will be filled later
set(netCDF_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(netCDF_FRAMEWORKS_FOUND "${netCDF_FRAMEWORKS}" "${netCDF_FRAMEWORK_DIRS}")

mark_as_advanced(netCDF_INCLUDE_DIRS
                 netCDF_INCLUDE_DIR
                 netCDF_INCLUDES
                 netCDF_DEFINITIONS
                 netCDF_LINKER_FLAGS_LIST
                 netCDF_COMPILE_DEFINITIONS
                 netCDF_COMPILE_OPTIONS_LIST
                 netCDF_LIBRARIES
                 netCDF_LIBS
                 netCDF_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to netCDF_LIBS and netCDF_LIBRARY_LIST
set(netCDF_LIBRARY_LIST netcdf)
set(netCDF_LIB_DIRS "C:/Users/johannes/.conan/data/netcdf/4.7.4/_/_/package/1566203a061d8ac21e9e8d90197c38a777e99c35/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_netCDF_DEPENDENCIES "${netCDF_FRAMEWORKS_FOUND} ${netCDF_SYSTEM_LIBS} HDF5::HDF5;CURL::CURL")

conan_package_library_targets("${netCDF_LIBRARY_LIST}"  # libraries
                              "${netCDF_LIB_DIRS}"      # package_libdir
                              "${_netCDF_DEPENDENCIES}"  # deps
                              netCDF_LIBRARIES            # out_libraries
                              netCDF_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "netCDF")                                      # package_name

set(netCDF_LIBS ${netCDF_LIBRARIES})

foreach(_FRAMEWORK ${netCDF_FRAMEWORKS_FOUND})
    list(APPEND netCDF_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND netCDF_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${netCDF_SYSTEM_LIBS})
    list(APPEND netCDF_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND netCDF_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(netCDF_LIBRARIES_TARGETS "${netCDF_LIBRARIES_TARGETS};HDF5::HDF5;CURL::CURL")
set(netCDF_LIBRARIES "${netCDF_LIBRARIES};HDF5::HDF5;CURL::CURL")

set(CMAKE_MODULE_PATH "C:/Users/johannes/.conan/data/netcdf/4.7.4/_/_/package/1566203a061d8ac21e9e8d90197c38a777e99c35/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/johannes/.conan/data/netcdf/4.7.4/_/_/package/1566203a061d8ac21e9e8d90197c38a777e99c35/" ${CMAKE_PREFIX_PATH})


########### COMPONENT netcdf VARIABLES #############################################

set(netCDF_netcdf_INCLUDE_DIRS "C:/Users/johannes/.conan/data/netcdf/4.7.4/_/_/package/1566203a061d8ac21e9e8d90197c38a777e99c35/include")
set(netCDF_netcdf_INCLUDE_DIR "C:/Users/johannes/.conan/data/netcdf/4.7.4/_/_/package/1566203a061d8ac21e9e8d90197c38a777e99c35/include")
set(netCDF_netcdf_INCLUDES "C:/Users/johannes/.conan/data/netcdf/4.7.4/_/_/package/1566203a061d8ac21e9e8d90197c38a777e99c35/include")
set(netCDF_netcdf_LIB_DIRS "C:/Users/johannes/.conan/data/netcdf/4.7.4/_/_/package/1566203a061d8ac21e9e8d90197c38a777e99c35/lib")
set(netCDF_netcdf_RES_DIRS )
set(netCDF_netcdf_DEFINITIONS "-DDLL_NETCDF")
set(netCDF_netcdf_COMPILE_DEFINITIONS "DLL_NETCDF")
set(netCDF_netcdf_COMPILE_OPTIONS_C "")
set(netCDF_netcdf_COMPILE_OPTIONS_CXX "")
set(netCDF_netcdf_LIBS netcdf)
set(netCDF_netcdf_SYSTEM_LIBS )
set(netCDF_netcdf_FRAMEWORK_DIRS )
set(netCDF_netcdf_FRAMEWORKS )
set(netCDF_netcdf_BUILD_MODULES_PATHS )
set(netCDF_netcdf_DEPENDENCIES HDF5::HDF5 CURL::CURL)
set(netCDF_netcdf_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)


########## FIND PACKAGE DEPENDENCY ##########################################################
#############################################################################################

include(CMakeFindDependencyMacro)

if(NOT HDF5_FOUND)
    find_dependency(HDF5 REQUIRED)
else()
    conan_message(STATUS "Conan: Dependency HDF5 already found")
endif()

if(NOT CURL_FOUND)
    find_dependency(CURL REQUIRED)
else()
    conan_message(STATUS "Conan: Dependency CURL already found")
endif()


########## FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #######################################
#############################################################################################

########## COMPONENT netcdf FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(netCDF_netcdf_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(netCDF_netcdf_FRAMEWORKS_FOUND "${netCDF_netcdf_FRAMEWORKS}" "${netCDF_netcdf_FRAMEWORK_DIRS}")

set(netCDF_netcdf_LIB_TARGETS "")
set(netCDF_netcdf_NOT_USED "")
set(netCDF_netcdf_LIBS_FRAMEWORKS_DEPS ${netCDF_netcdf_FRAMEWORKS_FOUND} ${netCDF_netcdf_SYSTEM_LIBS} ${netCDF_netcdf_DEPENDENCIES})
conan_package_library_targets("${netCDF_netcdf_LIBS}"
                              "${netCDF_netcdf_LIB_DIRS}"
                              "${netCDF_netcdf_LIBS_FRAMEWORKS_DEPS}"
                              netCDF_netcdf_NOT_USED
                              netCDF_netcdf_LIB_TARGETS
                              ""
                              "netCDF_netcdf")

set(netCDF_netcdf_LINK_LIBS ${netCDF_netcdf_LIB_TARGETS} ${netCDF_netcdf_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "C:/Users/johannes/.conan/data/netcdf/4.7.4/_/_/package/1566203a061d8ac21e9e8d90197c38a777e99c35/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/johannes/.conan/data/netcdf/4.7.4/_/_/package/1566203a061d8ac21e9e8d90197c38a777e99c35/" ${CMAKE_PREFIX_PATH})


########## TARGETS ##########################################################################
#############################################################################################

########## COMPONENT netcdf TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET netCDF::netcdf)
        add_library(netCDF::netcdf INTERFACE IMPORTED)
        set_target_properties(netCDF::netcdf PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${netCDF_netcdf_INCLUDE_DIRS}")
        set_target_properties(netCDF::netcdf PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${netCDF_netcdf_LIB_DIRS}")
        set_target_properties(netCDF::netcdf PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${netCDF_netcdf_LINK_LIBS};${netCDF_netcdf_LINKER_FLAGS_LIST}")
        set_target_properties(netCDF::netcdf PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${netCDF_netcdf_COMPILE_DEFINITIONS}")
        set_target_properties(netCDF::netcdf PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${netCDF_netcdf_COMPILE_OPTIONS_C};${netCDF_netcdf_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## GLOBAL TARGET ####################################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    if(NOT TARGET netCDF::netCDF)
        add_library(netCDF::netCDF INTERFACE IMPORTED)
    endif()
    set_property(TARGET netCDF::netCDF APPEND PROPERTY
                 INTERFACE_LINK_LIBRARIES "${netCDF_COMPONENTS}")
endif()

########## BUILD MODULES ####################################################################
#############################################################################################
########## COMPONENT netcdf BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${netCDF_netcdf_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
