

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findlibharu.cmake")
# Global approach
set(libharu_FOUND 1)
set(libharu_VERSION "2.3.0")

find_package_handle_standard_args(libharu REQUIRED_VARS
                                  libharu_VERSION VERSION_VAR libharu_VERSION)
mark_as_advanced(libharu_FOUND libharu_VERSION)


set(libharu_INCLUDE_DIRS "C:/Users/johannes/.conan/data/libharu/2.3.0/_/_/package/1f1549ce6e921d24d0b528117198f4d9f6a21d60/include")
set(libharu_INCLUDE_DIR "C:/Users/johannes/.conan/data/libharu/2.3.0/_/_/package/1f1549ce6e921d24d0b528117198f4d9f6a21d60/include")
set(libharu_INCLUDES "C:/Users/johannes/.conan/data/libharu/2.3.0/_/_/package/1f1549ce6e921d24d0b528117198f4d9f6a21d60/include")
set(libharu_RES_DIRS )
set(libharu_DEFINITIONS "-DHPDF_DLL")
set(libharu_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(libharu_COMPILE_DEFINITIONS "HPDF_DLL")
set(libharu_COMPILE_OPTIONS_LIST "" "")
set(libharu_COMPILE_OPTIONS_C "")
set(libharu_COMPILE_OPTIONS_CXX "")
set(libharu_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(libharu_LIBRARIES "") # Will be filled later
set(libharu_LIBS "") # Same as libharu_LIBRARIES
set(libharu_SYSTEM_LIBS )
set(libharu_FRAMEWORK_DIRS )
set(libharu_FRAMEWORKS )
set(libharu_FRAMEWORKS_FOUND "") # Will be filled later
set(libharu_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(libharu_FRAMEWORKS_FOUND "${libharu_FRAMEWORKS}" "${libharu_FRAMEWORK_DIRS}")

mark_as_advanced(libharu_INCLUDE_DIRS
                 libharu_INCLUDE_DIR
                 libharu_INCLUDES
                 libharu_DEFINITIONS
                 libharu_LINKER_FLAGS_LIST
                 libharu_COMPILE_DEFINITIONS
                 libharu_COMPILE_OPTIONS_LIST
                 libharu_LIBRARIES
                 libharu_LIBS
                 libharu_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to libharu_LIBS and libharu_LIBRARY_LIST
set(libharu_LIBRARY_LIST libhpdf)
set(libharu_LIB_DIRS "C:/Users/johannes/.conan/data/libharu/2.3.0/_/_/package/1f1549ce6e921d24d0b528117198f4d9f6a21d60/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_libharu_DEPENDENCIES "${libharu_FRAMEWORKS_FOUND} ${libharu_SYSTEM_LIBS} ZLIB::ZLIB;PNG::PNG")

conan_package_library_targets("${libharu_LIBRARY_LIST}"  # libraries
                              "${libharu_LIB_DIRS}"      # package_libdir
                              "${_libharu_DEPENDENCIES}"  # deps
                              libharu_LIBRARIES            # out_libraries
                              libharu_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "libharu")                                      # package_name

set(libharu_LIBS ${libharu_LIBRARIES})

foreach(_FRAMEWORK ${libharu_FRAMEWORKS_FOUND})
    list(APPEND libharu_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND libharu_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${libharu_SYSTEM_LIBS})
    list(APPEND libharu_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND libharu_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(libharu_LIBRARIES_TARGETS "${libharu_LIBRARIES_TARGETS};ZLIB::ZLIB;PNG::PNG")
set(libharu_LIBRARIES "${libharu_LIBRARIES};ZLIB::ZLIB;PNG::PNG")

set(CMAKE_MODULE_PATH "C:/Users/johannes/.conan/data/libharu/2.3.0/_/_/package/1f1549ce6e921d24d0b528117198f4d9f6a21d60/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/johannes/.conan/data/libharu/2.3.0/_/_/package/1f1549ce6e921d24d0b528117198f4d9f6a21d60/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET libharu::libharu)
        add_library(libharu::libharu INTERFACE IMPORTED)
        if(libharu_INCLUDE_DIRS)
            set_target_properties(libharu::libharu PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${libharu_INCLUDE_DIRS}")
        endif()
        set_property(TARGET libharu::libharu PROPERTY INTERFACE_LINK_LIBRARIES
                     "${libharu_LIBRARIES_TARGETS};${libharu_LINKER_FLAGS_LIST}")
        set_property(TARGET libharu::libharu PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${libharu_COMPILE_DEFINITIONS})
        set_property(TARGET libharu::libharu PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${libharu_COMPILE_OPTIONS_LIST}")
        
        # Library dependencies
        include(CMakeFindDependencyMacro)

        if(NOT ZLIB_FOUND)
            find_dependency(ZLIB REQUIRED)
        else()
            message(STATUS "Dependency ZLIB already found")
        endif()


        if(NOT PNG_FOUND)
            find_dependency(PNG REQUIRED)
        else()
            message(STATUS "Dependency PNG already found")
        endif()

    endif()
endif()

foreach(_BUILD_MODULE_PATH ${libharu_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
