########## MACROS ###########################################################################
#############################################################################################

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


########### FOUND PACKAGE ###################################################################
#############################################################################################

include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findpegtl.cmake")
set(pegtl_FOUND 1)
set(pegtl_VERSION "2.8.1")

find_package_handle_standard_args(pegtl REQUIRED_VARS
                                  pegtl_VERSION VERSION_VAR pegtl_VERSION)
mark_as_advanced(pegtl_FOUND pegtl_VERSION)

set(taocpp_COMPONENTS taocpp::pegtl)

if(pegtl_FIND_COMPONENTS)
    foreach(_FIND_COMPONENT ${pegtl_FIND_COMPONENTS})
        list(FIND taocpp_COMPONENTS "taocpp::${_FIND_COMPONENT}" _index)
        if(${_index} EQUAL -1)
            conan_message(FATAL_ERROR "Conan: Component '${_FIND_COMPONENT}' NOT found in package 'taocpp'")
        else()
            conan_message(STATUS "Conan: Component '${_FIND_COMPONENT}' found in package 'taocpp'")
        endif()
    endforeach()
endif()

########### VARIABLES #######################################################################
#############################################################################################


set(taocpp_INCLUDE_DIRS "C:/Users/johannes/.conan/data/taocpp-pegtl/2.8.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(taocpp_INCLUDE_DIR "C:/Users/johannes/.conan/data/taocpp-pegtl/2.8.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(taocpp_INCLUDES "C:/Users/johannes/.conan/data/taocpp-pegtl/2.8.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(taocpp_RES_DIRS )
set(taocpp_DEFINITIONS )
set(taocpp_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(taocpp_COMPILE_DEFINITIONS )
set(taocpp_COMPILE_OPTIONS_LIST "" "")
set(taocpp_COMPILE_OPTIONS_C "")
set(taocpp_COMPILE_OPTIONS_CXX "")
set(taocpp_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(taocpp_LIBRARIES "") # Will be filled later
set(taocpp_LIBS "") # Same as taocpp_LIBRARIES
set(taocpp_SYSTEM_LIBS )
set(taocpp_FRAMEWORK_DIRS )
set(taocpp_FRAMEWORKS )
set(taocpp_FRAMEWORKS_FOUND "") # Will be filled later
set(taocpp_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(taocpp_FRAMEWORKS_FOUND "${taocpp_FRAMEWORKS}" "${taocpp_FRAMEWORK_DIRS}")

mark_as_advanced(taocpp_INCLUDE_DIRS
                 taocpp_INCLUDE_DIR
                 taocpp_INCLUDES
                 taocpp_DEFINITIONS
                 taocpp_LINKER_FLAGS_LIST
                 taocpp_COMPILE_DEFINITIONS
                 taocpp_COMPILE_OPTIONS_LIST
                 taocpp_LIBRARIES
                 taocpp_LIBS
                 taocpp_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to taocpp_LIBS and taocpp_LIBRARY_LIST
set(taocpp_LIBRARY_LIST )
set(taocpp_LIB_DIRS )

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_taocpp_DEPENDENCIES "${taocpp_FRAMEWORKS_FOUND} ${taocpp_SYSTEM_LIBS} ")

conan_package_library_targets("${taocpp_LIBRARY_LIST}"  # libraries
                              "${taocpp_LIB_DIRS}"      # package_libdir
                              "${_taocpp_DEPENDENCIES}"  # deps
                              taocpp_LIBRARIES            # out_libraries
                              taocpp_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "taocpp")                                      # package_name

set(taocpp_LIBS ${taocpp_LIBRARIES})

foreach(_FRAMEWORK ${taocpp_FRAMEWORKS_FOUND})
    list(APPEND taocpp_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND taocpp_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${taocpp_SYSTEM_LIBS})
    list(APPEND taocpp_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND taocpp_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(taocpp_LIBRARIES_TARGETS "${taocpp_LIBRARIES_TARGETS};")
set(taocpp_LIBRARIES "${taocpp_LIBRARIES};")

set(CMAKE_MODULE_PATH "C:/Users/johannes/.conan/data/taocpp-pegtl/2.8.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/johannes/.conan/data/taocpp-pegtl/2.8.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/" ${CMAKE_PREFIX_PATH})


########### COMPONENT pegtl VARIABLES #############################################

set(taocpp_pegtl_INCLUDE_DIRS "C:/Users/johannes/.conan/data/taocpp-pegtl/2.8.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(taocpp_pegtl_INCLUDE_DIR "C:/Users/johannes/.conan/data/taocpp-pegtl/2.8.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(taocpp_pegtl_INCLUDES "C:/Users/johannes/.conan/data/taocpp-pegtl/2.8.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(taocpp_pegtl_LIB_DIRS )
set(taocpp_pegtl_RES_DIRS )
set(taocpp_pegtl_DEFINITIONS )
set(taocpp_pegtl_COMPILE_DEFINITIONS )
set(taocpp_pegtl_COMPILE_OPTIONS_C "")
set(taocpp_pegtl_COMPILE_OPTIONS_CXX "")
set(taocpp_pegtl_LIBS )
set(taocpp_pegtl_SYSTEM_LIBS )
set(taocpp_pegtl_FRAMEWORK_DIRS )
set(taocpp_pegtl_FRAMEWORKS )
set(taocpp_pegtl_BUILD_MODULES_PATHS )
set(taocpp_pegtl_DEPENDENCIES )
set(taocpp_pegtl_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)


########## FIND PACKAGE DEPENDENCY ##########################################################
#############################################################################################

include(CMakeFindDependencyMacro)


########## FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #######################################
#############################################################################################

########## COMPONENT pegtl FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(taocpp_pegtl_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(taocpp_pegtl_FRAMEWORKS_FOUND "${taocpp_pegtl_FRAMEWORKS}" "${taocpp_pegtl_FRAMEWORK_DIRS}")

set(taocpp_pegtl_LIB_TARGETS "")
set(taocpp_pegtl_NOT_USED "")
set(taocpp_pegtl_LIBS_FRAMEWORKS_DEPS ${taocpp_pegtl_FRAMEWORKS_FOUND} ${taocpp_pegtl_SYSTEM_LIBS} ${taocpp_pegtl_DEPENDENCIES})
conan_package_library_targets("${taocpp_pegtl_LIBS}"
                              "${taocpp_pegtl_LIB_DIRS}"
                              "${taocpp_pegtl_LIBS_FRAMEWORKS_DEPS}"
                              taocpp_pegtl_NOT_USED
                              taocpp_pegtl_LIB_TARGETS
                              ""
                              "taocpp_pegtl")

set(taocpp_pegtl_LINK_LIBS ${taocpp_pegtl_LIB_TARGETS} ${taocpp_pegtl_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "C:/Users/johannes/.conan/data/taocpp-pegtl/2.8.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/johannes/.conan/data/taocpp-pegtl/2.8.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/" ${CMAKE_PREFIX_PATH})


########## TARGETS ##########################################################################
#############################################################################################

########## COMPONENT pegtl TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET taocpp::pegtl)
        add_library(taocpp::pegtl INTERFACE IMPORTED)
        set_target_properties(taocpp::pegtl PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${taocpp_pegtl_INCLUDE_DIRS}")
        set_target_properties(taocpp::pegtl PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${taocpp_pegtl_LIB_DIRS}")
        set_target_properties(taocpp::pegtl PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${taocpp_pegtl_LINK_LIBS};${taocpp_pegtl_LINKER_FLAGS_LIST}")
        set_target_properties(taocpp::pegtl PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${taocpp_pegtl_COMPILE_DEFINITIONS}")
        set_target_properties(taocpp::pegtl PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${taocpp_pegtl_COMPILE_OPTIONS_C};${taocpp_pegtl_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## GLOBAL TARGET ####################################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    if(NOT TARGET taocpp::taocpp)
        add_library(taocpp::taocpp INTERFACE IMPORTED)
    endif()
    set_property(TARGET taocpp::taocpp APPEND PROPERTY
                 INTERFACE_LINK_LIBRARIES "${taocpp_COMPONENTS}")
endif()

########## BUILD MODULES ####################################################################
#############################################################################################
########## COMPONENT pegtl BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${taocpp_pegtl_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
